sets.append("crabs")
wcards-crabs = [
    "A $50 cup of coffee literally made from cat shit.",
    "A beard longer than 12 inches.",
    "A four-inch clit.",
    "A hamster with a throbbing erection.",
    "A mazel tov cocktail.",
    "A nugget of poo roughly the size and shape of a crouton.",
    "A prehensile penis.",
    "A sexually aggressive koala.",
    "A shockingly flatulent bobcat.",
    "A strong, independent woman who don't need no man.",
    "A tossed salad.",
    "An asexual bonobo.",
    "An entire bottle of Jagermeister.",
    "An extra-large can of Bone Bashful brand Chinchilla Pudding Sauce.",
    "An Oosik, or Inuit war club made from the penis bone of a walrus.",
    "An overly-enthusiastic prostate exam.",
    "An unsurprising rash.",
    "Axl Rose.",
    "Bacon that can feel pain.",
    "Bacon-flavored lube",
    "Being born with a tail.",
    "Being kicked in the ovaries.",
    "Being punk in drublic.",
    "Being raped to sleep by dickwolves.",
    "Belching out the lyrics to 'Hey Jude'.",
    "Bono. Just... Bono.",
    "Bronies.",
    "Cockasaurus rex: the horniest dinosaur of them all.",
    "Cocktimus Prime: the laser-guided dildo rocket.",
    "Costco food samples.",
    "Death by snu-snu.",
    "Droppin' the mic.",
    "Enrolling in clown school.",
    "Erotic balloon animals.",
    "Explaining how I got the nickname 'Nibbleberries'.",
    "Ezekiel 23:20 'There she lusted after her lovers, whose genitals were like those of donkeys and whose emission was like that of horses.'",
    "Flop sweat.",
    "Gilbert Gottfried's voice.",
    "Giving Anne Frank a drum kit for her birthday.",
    "Giving the tumor a cutesy name.",
    "Googling 'Betty White nude'.",
    "Grandma's wet, sloppy kisses.",
    "Honey Boo Boo shotgunning a 2-liter bottle of 'go-go juice'.",
    "Insisting that Jesus is technically a zombie.",
    "JJ Abrams putting lens flares all over everything.",
    "Joe Biden getting his freak on.",
    "Joffrey Baratheon, the loathsome little shit.",
    "Lego recreations of famous porn scenes.",
    "Michele Bachmann furiously masturbating with a coathanger.",
    "Mitt Romney doing a burlesque routine in a giant champagne glass.",
    "Monkey torture.",
    "My level 90 night elf, Leafshit Puddingsbane.",
    "Natalie Portman naked, petrified, and covered in hot grits.",
    "Officially no longer giving a shit.",
    "Plato's Allegory of the Cave or some other pretentious bullshit.",
    "Posting on /r/gonewild/.",
    "Pretending to be a malfunctioning robot.",
    "Pretending to have the hiccups.",
    "Pronouncing 'quinoa' properly.",
    "Racist ninjas.",
    "Raptor Jesus.",
    "Reluctant anal.",
    "S'more Schnapps.",
    "Selling out.",
    "Sexy witches.",
    "Slightly more than 3 ounces of cum.",
    "Steaming hot lemonade.",
    "Struggle snuggles.",
    "That 'not-so-fresh' feeling.",
    "The combined fat from all of the Kardashians' liposuction procedures.",
    "The fabled Mongolian Death Worm.",
    "The green apple splatters.",
    "The Slender Man.",
    "The TARDIS.",
    "Touching each other's butts.",
    "Using teeth.",
    "Van Gogh's severed ear.",
    "Weaponized ebola.",
    "Wielding a toddler as a weapon.",
    "WINNING!!",
    "Yoga pants.",
    "A 5 lb. bag of gummy bears.",
    "A bachelor's degree in communication.",
    "A bit o' the ol' slap and tickle.",
    "A bitchin' Camaro",
    "A blanket with a hole in it.",
    "A breakfast sausage with serious emotional problems.",
    "A chair that likes to rape people.",
    "A cunning stunt.",
    "A good schtupping.",
    "A gratuitous claymation sequence.",
    "A hairshirt.",
    "A husband bulge.",
    "A jury of your peers.",
    "A sense of resignation.",
    "A slack-jawed yokel.",
    "A stinky pinky.",
    "A tender rogering.",
    "A warm, gently fragrant biscuit.",
    "A were-salmon.",
    "A younger, vastly more attractive spouse.",
    "An angry little man.",
    "An effeminate southern homophobe.",
    "Applying to a new guild",
    "Barfing into a tiny, bejeweled handbag.",
    "Being able to name all of the different kinds of olives.",
    "Being circumcised with a deli slicer.",
    "Being small but perfectly well formed.",
    "Bitch tits.",
    "Blistering barnacles!",
    "Bourbon pong.",
    "Cockissimo Fantastico, the legendary lover with a wondrous wang.",
    "Cockulous Maximus, tremendous tallywacker of Tripoli.",
    "Gazpacho tactics.",
    "Giving your pet lamb a Brazilian.",
    "Hakuna matata, motherfucker.",
    "Her dry, scaly hands.",
    "Hooking up at a Tegan & Sarah concert.",
    "Japanese rope technique.",
    "Kentucky Fried Children.",
    "Killing hobos.",
    "Making vigorous love to a Taco Bell Beefy 5-Layer Burrito.",
    "Mesothelioma.",
    "Minimum wage.",
    "Mongolian 'beef'.",
    "Not being too smelly, you know, in the cellar. Down Below.",
    "One Direction.",
    "One whose nether regions are vast and backoning, like unto a corridor down which a frankfurther might be thrown.",
    "Opening for Sigur Ros.",
    "Painal.",
    "Paula Deen's dietitian.",
    "Poop soup.",
    "Pooping in public.",
    "Reptilians.",
    "Rich Corinthian leather.",
    "Rock bottom.",
    "Running around like a guy with his chicken cut off.",
    "Self-medicating.",
    "Self-replicating fudge.",
    "Slowly waving an oversized Jamaican flag.",
    "Something Elon Musk thought up while floating six inches above the floor in a meditative trance.",
    "Spiking the juice at AA.",
    "Sploosh!",
    "Swallowing a cue ball.",
    "Tacos.",
    "Ted Nugent's cold, dead hands.",
    "That thing with the spoon.",
    "The Cliterati.",
    "The creative use of a pool noodle.",
    "The smooth, unblemished skin of a child.",
    "The soft love-honks of a lusty goose.",
    "The whole goddamned thing.",
    "Those creamy atheist thighs.",
    "Titty sprinkles.",
    "Tufted ears.",
    "Uncontrollably retching at the mere mention of mayonnaise.",
    "Using a zip-tie as an impromptu cock-ring.",
    "Using tears as lubricant.",
    "Wearing a blue fox fursuit on Casual Friday.",
    "Wearing your IUD into an MRI.",
    ]
bcards-crabs = [
    "__________: Just sayin'.",
    "__________: not even once.",
    "According to a new UN treaty, __________ now qualifies as a weapon of mass destruction.",
    "Ever since 'the incident', every time I close my eyes, I still see __________.",
    "Gentlemen, I'm sure you're wondering why I asked you here this evening. It's a long story, but it all began with __________.",
    "How did I get this restraining order?",
    "How did I hurt my back?",
    "How did my grandparents make it through the Great Depression?",
    "I am become __________, destroyer of worlds.",
    "I'm so hungry I could eat __________.",
    "If you want a picture of the future, imagine a boot stamping on __________--forever.",
    "In a move that has Hollywood insiders baffled, the producers of American Idol have decided to replace host Ryan Seacrest with __________.",
    "In my opinion, __________ is grounds for justifiable homicide.",
    "It took seven years in a remote Tibetan monastery, but I finally learned the art of __________.",
    "Like Midas reborn, everything she touches turns to __________.",
    "Oh my God! They killed __________! You bastards!",
    "The best part of waking up is __________.",
    "Tonight on 'My Super Sweet 16', Stephani's parents give her __________.",
    "What was one of the rejected flavors for Baskin-Robbins ice cream?",
    "Why won't they let me in Chuck E. Cheese's anymore?",
    "William Shatner's shocking new autobiography is titled '__________: The Final Frontier'.",
    "__________: it's magically delicious.",
    "__________? That's what she said.",
    "'You have my sword.' 'And you have my bow.' 'And my __________!'",
    "A new Russian dash-cam video shows __________, right there in the middle of the street!",
    "Apple has announced a new device that promises to revolutionize the way we think about __________.",
    "Audiences at Sundance were traumatized by Lars von Trier's controversial new film, '__________'.",
    "Dear Dan Savage, Please help. I am unable to achieve orgasm without __________.",
    "Experts say that without careful management and conservation, __________ will disappear within our lifetimes.",
    "From the people who brough you Sharktopus and Sharknato, Syfy's next horror film combines sharks with __________.",
    "Having abandoned his pleas for a return to the gold standard, Ron Paul is now promoting a __________-based economy.",
    "What's the name of my latest music project?",
    "I don't care what people say, __________ is not a crime.",
    "I have to admit... it took me a while to agree to it, but incorporating __________ into our wedding ceremony is a decision I will never regret.",
    "I quit my job as a bartender the night some jackass left me __________ as a tip.",
    "I think I need to take Fluffums to puppy training---he has this terrible habit of __________.",
    "I wish it were something simple, like peanuts or shellfish, but my doctor tells me I'm actually allergic to __________.",
    "If people wouldn't be so quick to judge, I would give __________ to anyone in this channel in a heartbeat.",
    "Michelle Obama outraged conservatives when she implied that __________ maybe wasn't such a bad thing.",
    "My tour of the White House radically escalated when Secret Service caught a glimpse of __________ in my bag.",
    "Now that he has retired, Pope Benedict can finally devote time to his true passion: __________.",
    "Oh, so you think you're too good for us now, little miss '__________'!",
    "WANTED: a clean, well-lit place for __________.",
    "When you play the Game Of __________, you win or you die.",
    "Why won't anyone sit with me?",
]

bcards2-crabs = [
    "A wild __________ appears! You used __________! It's super effective!", 
    "I was once sent to the HR department for an incident involving __________ and __________.",
    "I'm gonna go build my own theme park! With __________! And __________!",
    "PornHub.com's single most popular video features __________ and __________.", 
    "So then he says, 'If you want to make this relationship work, you need to give up __________ and __________.' As. If.",
    "Thanks to __________, I now have a crippling fear of __________.",
    "The last two items on my bucket list are __________ and __________.",  
    "When I'm dating somebody, I can overlook __________, but __________ is a deal-breaker.",
    "An ounce of __________ is worth a pound of __________.",
    "Bentley's latest ultra-high-end luxury sedan comes complete with __________ and __________.",
    "Dear, your father and I found __________ and __________ in your bedroom. I'm shocked, and frankly just a little disappointed.",
    "I got some strange looks in the checkout line when the cashier noticed __________ and __________ in my cart.",
    "Netflix's new original series is a sitcom based around __________ and __________.",
    "The NSA wants to talk to me about an email I sent out containing phrases like __________ and __________.",
    "When I've seriously fucked up and need to make amends, what can I give my significant other to show them I am truly remorseful?",
    "Yea, though I walk through the valley of __________, I will fear no __________.",
]
