wcards-stl = [
    "A beluga whale.",
    "Rambone.",
    "Illinois drivers.",
    "A delicious bag of Red Hot Riplets.",
    "The Mississippi River.",
    "Chesterfield.",
    "Provel cheese.",
    "The city/county debate.",
    "Dammit Karen!",
    "An ass-five.",
    "DTbot.",
    "Lolita cosplay.",
    "Ted Drewes.",
    "Breadco.",
    "David Freese.",
    "Tony La Russa.",
    "Albert Pujols.",
    "Yadi.",
    "Matt Carpenter.",
    "The Cubs.",
    "The Red Sox.",
    "The Stan Span.",
    "Calling highway 40 I-64.",
    "North County.",
    "Imo's pizza.",
    "Gooey butter cake.",
    "QuikTrip.",
    "Toasted ravioli.",
    "The Loop.",
    "The Arch.",
    "Forest Park.",
    "Fast Eddie's.",
    "Mike Matheny.",
    "Jim Edmonds.",
    "misspwn.",
    "DT",
    "Living in Fenton.",
    "Jenn's sex toy collection.",
    "Waking up in a bed at Delmar Gardens.",
    "Pappy's Barbeque.",
    "Asking 'Where did you go to high school?'",
    "Gambling on the boat.",
    "A Veiled Prophet Parade Queen.",
    "Finding out you've been cat-fished.",
    "Boobs of all shapes and sizes.",
    "rikkitikki's smokin' hot bod.",
    "Nut Butter.",
    "Leaving no bitches unswooned.",
    "Brawndo, the thirst mutilator.",
    "Bill Cosby seductively rubbing his nipples with puddin pops.",
    "Being hit by the toilet seat of a space station re-entering the atmosphere.",
    "Packs of scissors that you need scissors to open.",
    "Lumpy Space Princess.",
    "Young faces with braces.",
    "Liking big butts, and being unable to lie about it.",
    "Touching someone's genitalia in the caves at the City Museum.",
    "Pegging.",
    "Joe Buck's massive forehead.",
    "Pretending the metro east doesn't exist.",
    "New Town St. Charles.",
    "Being from Jefferson County.",
    "Puppy mills.",
    "Tom Shane's dull voice.",
    "Thinking Shane Co is a local business.",
    "Blow-up doll incest.",
    "A moustachioed car full of hipsters.",
    "A mysterious stain in the back of a cab.",
    "A terrible hand of CAH cards.",
    "Drinking negative beers.",
    "A moustache ride from Lyft.",
    "An Indian rope burn.",
    "A poopsack.",
    "Snail trails.",
    "A suspicious cupcake.",
    "Disposing of a body.",
    "Hookers and blow.",
    "Resting Bitch Face.",
    "Omega037.",
    "A ginger beard.",
    "A timely deflection.",
    "A potato dressed as a boy pretending to be a man.",
    "Shipping Evin and frisv.",
    "Feeling inspired by Hitler.",
    "Fighting sarcasm with more sarcasm.",
    "The Muny.",
    "Being Illinnoying.",
    "Constantly talking about living in Japan.",
    "Fruit Stripe Gum.",
    "A neckbeard tipping his fedora.",
    "A Men's Rights Activist.",
    "A Pick Up Artist.",
    "/r/theredpill",
    "Setting a QuikTrip on fire.",
    "Putting bacon in everything.",
    "Giving a running play-by-play of your night out.",
    "The Gay of the Day.",
    "A gay robot.",
    "Groot.",
    "grobend's semi-flaccid penis.",
    "The Stig.",
    "Jeremy Clarkson.",
    "A gentleman's sausage.",
    "Gentleman's relish.",
    "res0.",
    "bbbeluga.",
    "nerddtvg.",
    "GreetingsADM.",
    "spif.",
    "monkers.",
    "rikkitikki.",
    "Peeing in a girl's butt.",
    "Big Dick Problems.",
    "A wink from Primesauce.",
    "Ms. New Booty.",
    "The Players' Club.",
    "Whips and chains.",
    "A sex swing.",
    "A steam-powered fucking machine.",
    "A girl dressed as a pinata.",
    "A hands-free blowjob.",
    "Calming your tits.",
    "secretninjaket's rack.",
#    "Mr. Rogers balls deep in an underage prostitute.",
    "A gum-job from Grandma.",
    "Getting dust in your hoo-hah.",
    "Poop bang.",
    "Breakfast at the Cracker Barrel.",
    "A shitty suggestion for a new card.",
    "Fucklings.",
    "Pumpkin spice flavored condoms.",
    "Literally sleeping with the fishes.",
    "k27463 cosplaying as Thomas the Tank Engine.",
    "A Pomplamoose show.",
    "Gluing pubes to my face in lieu of growing a beard.",
    "Forgetting about Primus.",
    "Forgetting about Dre.",
    "Two trailer park girls going 'round the outside.",
    "Big money, no whammies.",
    "A dildo made of frozen HIV.",
    "Getting 9/10 in a trivia category you suggested.",
    "Naming everything after poop.",
    "Having a million friends but not really knowing anybody.",
    "Being part of the 1%.",
    "Joining an unpopular movement.",
    "A tree falling silently in an empty forest.",
    "#GamerGate",
    "The Boobseum",
    "Peeing in Forest Park.",
    "tadni.",
    "A new technique for peeing while driving.",
    "Nerfdude.",
    "Showing up at someone's workplace unannounced and calling it a meetup.",
    "Turning around in res0's driveway.",
    "Too Many Cooks",
    "Creating a reference experience for the spank bank.",
    "Three grandmas trying marijuana for the first time.",
    "Hamster-sized snowflakes.",
    "Electropop.",
    "ajwalsh44.",
    "||cw.",
    "zeryl.",
    "Electropop's virginity.",
    "Inappropriate use of Comic Sans.",
    "anotherbofh.",
]

bcards-stl = [
    "Instead of merging with St Louis County, the city will merge with __________.",
    "The next big event moving to Chesterfield is __________.",
    "The new seasonal brew from Schlafly is called __________.",
    "It's not the heat, it's __________.",
    "The newest stranger creation at Strange Donuts is called __________.",
    "St. Charles County residents will never allow a Metrolink extension, for fear of __________.",
    "If you don't like __________, wait 5 minutes.",
    "Meet me at __________!",
    "The new Ballpark Village dress code prohibits __________.",
    "__________. Not even once.",
    "__________ is now 10 for $10 at Schnucks.",
    "One of the goats at Grant's Farm tried to eat __________.",
    "The only thing St Louis wants more than an IKEA is __________.",
    "I don't pee in a girl's butt unless I'm __________! Because I'm a fucking gentleman!",
    "The weird kids from high school never stop being weird, we just get better at __________.",
    "What is the Ultimate Answer of Life, The Universe and Everything?",
    "My new favorite subreddit is r/__________.",
    "TONY STARK BUILT __________ IN A CAVE! WITH A BOX OF SCRAPS!!!",
    "How crazy would that be, you are about get it on with someone, pull off their shirt and BLAM __________.",
    "What is the Hokey-pokey really all about?",
    "If __________ were an Olympic Sport, I'd win the gold medal.",
    "You know how I know you're gay? You like __________.",
    "Thanks to autocorrect, I sent my boss a text telling them I would be busy working on __________ this weekend.",
    "When I went to college I majored in __________.",
        "Carol House Furniture: because you like __________.",
    "Now you have a friend in the __________ business!",
    "The square beyond __________!",
    "A judge has issued a restraining order against a startup bringing __________ to the people of St Louis.",
    "__________. THANKS OBAMA",
    "What's the theme for rikkitikki's newest outfit?",
    "We can't take misspwn anywhere because she likes __________.",
    "What's bbbeluga excited about?",
    "The first thing people usually notice about me is __________.",
    "I'm really good at __________.",
    "res0 had to rewrite part of the CAH bot because of __________.",
    "GreetingsADM got his nickname from __________.",
    "Chank is marked 'gone' because of __________.",
    "nerddtvg got upset because nobody thought __________ was funny.",
    "If it weren't for __________, I wouldn't have spent that year in college.",
    "The only thing keeping Katty from moving to St Louis is __________.",
    "Why does Charles 'Ed' Brown, attorney at law, have to wear an eye patch?",
    "Lemmons had to close because the owner was sick of __________.",
    "What caused the citizens of North County to riot?",
    "At the trade deadline, the Cardinals announced their new secret weapon: __________.",
    "St Louis County Police were heavily criticized for their use of __________.",
    "spif creeped everyone out because of his obsession with __________.",
    "Once again, tadni is complaining because of his sister's involvement with __________.",
    "The latest awareness campaign stunt involves __________.",
    "Top Gear's Jeremy Clarkson recently got blasted by the papers for his comments on __________.",
    "Open the door, get on the floor. Everybody walk __________.",
    "The latest addition to k27463's model train setup is __________.",
    "Because zeryl lives in Troy, he can't enjoy __________ with the rest of us.",
    "What did I get instead of a beer when I gave DTbot a high five?",
    "What's the latest feature to be added to DLbot?",
    "If ||cw got more involved with __________, there would definitely be a card written about him.",
    "dolemite7 is looking for a unicode emoticon that successfully communicates the feeling of __________.",
    "Charter experienced a nationwide service interruption because of __________.",
    "What is always DeliriumTremens' fault?",
    "What's TenthTARDIS most looking forward to in the new series of Doctor Who?",
    "Primesauce identifies as a cloud because of __________.",
    "The Rams are finally moving to LA after a disappointing performance against __________.",
    "How is babby formed? How girl get pragnent?",
    "Booty booty booty booty rockin' __________.",
    "For my New Year's resolution, I'm planning on improving __________.",
    "We, the people of the United States, in order to form a more perfect union, [...] do ordain and establish __________.",
    "What's secretninjaket's secret?",
    "Evin gave up the glamorous life of a journalist in order to pursue __________.",
    "Would you be mine? Could you be mine? Won't you be __________?",
    "I lost my faith in God when I learned about __________.",
    "I like __________ and I cannot lie.",
    "You can tell it's a new season because all the stores are selling __________.",
    "What's the newest product to be offered in pumpkin spice flavor?",
    "Today is National __________ Day!",
    "Chank and res0 can't stop fighting about __________.",
    "What name will the trivia team use this week?",
    "Anything, including __________, can be a dildo if you're brave enough.",
    "spif has a friend that's familiar with __________.",
    "__________ is a lie.",
    "I got a creepy message asking for pics of __________.",
    "More people die each year from __________ than from Ebola.",
    "Why did I get sent home from school?",
    "Actually, it's not about __________, it's about ethics in journalism.",
    "For Halloween I'm dressing up as a slutty version of __________.",
    "Casino QueeEEEeen, home of __________!",
    "Why did I have to register as a sex offender?",
    "What was Nerfdude's favorite experience on his recent trip to Japan?",
    "__________? That shit cray.",
    "What is Electropop saving herself for?",
    "* anotherbofh is now known as bofh|__________.",
]

bcards2-stl = [
    "What will the categories be for the next two rounds of trivia?",
    "Omega037 started an argument by suggesting that __________ and __________ were the same thing.",
    "monkers invited all the girls out for __________ and __________.",
    "__________ and __________? Too soon!",
    "The specials for today are __________ and __________.",
    "res0 is working on a new song that incorporates __________ and __________.",
    "I can't wait for __________ and __________ to coincide. But not in real life. Just in the cards.",
    "My surefire pickup line involves asking about __________ and suggesting that we go back to my place for __________.",
    "If you squint your eyes just right, __________ looks just like __________.",
    "rikkitikki is sad she moved to San Diego because she'll miss out on __________ and __________.",
]
