def wcards():
    return [
    "A Gypsy curse.",
    "A moment of silence.",
    "A sausage festival.",
    "An honest cop with nothing left to lose.",
    "Famine.",
    "Flesh-eating bacteria.",
    "Flying sex snakes.",
    "Not giving a shit about the Third World.",
    "Sexting.",
    "Shapeshifters.",
    "Porn stars.",
    "Raping and pillaging.",
    "72 virgins.",
    "A drive-by shooting.",
    "A time travel paradox.",
    "Authentic Mexican cuisine.",
    "Bling.",
    "Consultants.",
    "Crippling debt.",
    "Daddy issues.",
    "The Donald Trump Seal of Approval.",
    "Dropping a chandelier on your enemies and riding the rope up.",
    "Former President George W. Bush.",
    "Full frontal nudity.",
    "Hormone injections.",
    "Laying an egg.",
    "Getting naked and watching Nickelodeon.",
    "Pretending to care.",
    "Public ridicule.",
    "Sharing needles.",
    "Boogers.",
    "The inevitable heat death of the universe.",
    "The miracle of childbirth.",
    "The Rapture.",
    "Whipping it out.",
    "White privilege.",
    "Wifely duties.",
    "The Hamburglar.",
    "AXE Body Spray.",
    "The Blood of Christ.",
    "Horrifying laser hair removal accidents.",
    "BATMAN!!!",
    "Agriculture.",
    "A robust mongoloid.",
    "Natural selection.",
    "Coat hanger abortions.",
    "Eating all of the cookies before the AIDS bake-sale.",
    "Michelle Obama's arms.",
    "The World of Warcraft.",
    "Swooping.",
    "Obesity.",
    "A homoerotic volleyball montage.",
    "Lockjaw.",
    "A mating display.",
    "Testicular torsion.",
    "All-you-can-eat shrimp for $4.99.",
    "Domino's Oreo Dessert Pizza.",
    "Kanye West.",
    "Hot cheese.",
    "Raptor attacks.",
    "Taking off your shirt.",
    "Smegma.",
    "Alcoholism.",
    "A middle-aged man on roller skates.",
    "The Care Bear Stare.",
    "Bingeing and purging.",
    "Oversized lollipops.",
    "Self-loathing.",
    "Children on leashes.",
    "Half-assed foreplay.",
    "The Holy Bible.",
    "German dungeon porn.",
    "Being on fire.",
    "Teenage pregnancy.",
    "Gandhi.",
    "Leaving an awkward voicemail.",
    "Uppercuts.",
    "Customer service representatives.",
    "An erection that lasts longer than four hours.",
    "My genitals.",
    "Picking up girls at the abortion clinic.",
    "Science.",
    "Not reciprocating oral sex.",
    "Flightless birds.",
    "A good sniff.",
    "Waterboarding.",
    "A balanced breakfast.",
    "Historically black colleges.",
    "Actually taking candy from a baby.",
    "The Make-A-Wish Foundation.",
    "A clandestine butt scratch.",
    "Passive-aggressive Post-it notes.",
    "The Chinese gymnastics team.",
    "Switching to Geico.",
    "Peeing a little bit.",
#    "Home video of Oprah sobbing into a Lean Cuisine.",
    "Nocturnal emissions.",
    "The Jews.",
    "My humps.",
    "Powerful thighs.",
    "Winking at old people.",
    "Mr. Clean, right behind you.",
    "A gentle caress of the inner thigh.",
    "Sexual tension.",
    "The forbidden fruit.",
    "Skeletor.",
    "Fancy Feast.",
    "Being rich.",
    "Sweet, sweet vengeance.",
    "Republicans.",
    "A gassy antelope.",
    "Natalie Portman.",
    "Copping a feel.",
    "Kamikaze pilots.",
    "Sean Connery.",
    "The homosexual agenda.",
    "The hardworking Mexican.",
    "A falcon with a cap on its head.",
    "Altar boys.",
    "The Kool-Aid Man.",
    "Getting so angry that you pop a boner.",
    "Free samples.",
    "A big hoopla about nothing.",
    "Doing the right thing.",
    "The Three-Fifths compromise.",
    "Lactation.",
    "World peace.",
    "RoboCop.",
    "Chutzpah.",
    "Justin Bieber.",
    "Oompa-Loompas.",
    "Inappropriate yodeling.",
    "Puberty.",
    "Ghosts.",
    "An asymmetric boob job.",
    "Vigorous jazz hands.",
    "Fingering.",
#    "Glenn Beck catching his scrotum on a curtain hook.",
    "GoGurt.",
    "Police brutality.",
    "John Wilkes Booth.",
    "Preteens.",
    "Scalping.",
    "Stifling a giggle at the mention of Hutus and Tutsis.",
    "\"Tweeting.\"",
    "Darth Vader.",
    "A sad handjob.",
    "Exactly what you'd expect.",
    "Expecting a burp and vomiting on the floor.",
    "Adderall.",
    "Embryonic stem cells.",
    "Tasteful sideboob.",
    "Panda sex.",
    "An icepick lobotomy.",
    "Tom Cruise.",
    "Mouth herpes.",
    "Sperm whales.",
    "Homeless people.",
    "Third base.",
    "Incest.",
    "Pac-Man uncontrollably guzzling cum.",
    "A mime having a stroke.",
    "Hulk Hogan.",
    "God.",
    "Scrubbing under the folds.",
    "Golden showers.",
    "Emotions.",
    "Licking things to claim them as your own.",
    "Pabst Blue Ribbon.",
    "The placenta.",
    "Spontaneous human combustion.",
    "Friends with benefits.",
    "Finger painting.",
    "Old-people smell.",
    "Dying of dysentery.",
    "My inner demons.",
    "A Super Soaker full of cat pee.",
    "Aaron Burr.",
    "Cuddling.",
    "The chronic.",
    "Cockfights.",
    "Friendly fire.",
    "Ronald Reagan.",
    "A disappointing birthday party.",
    "A sassy black woman.",
    "Mathletes.",
    "A tiny horse.",
    "William Shatner.",
    "Riding off into the sunset.",
    "An M. Night Shyamalan plot twist.",
    "Jew-fros.",
    "Mutually-assured destruction.",
    "Pedophiles.",
    "Yeast.",
    "Grave robbing.",
    "Eating the last known bison.",
    "Catapults.",
    "Poor people.",
    "Forgetting the Alamo.",
    "The Hustle.",
    "The Force.",
    "Wiping her butt.",
    "Intelligent design.",
    "Loose lips.",
    "AIDS.",
    "Pictures of boobs.",
    "The Ubermensch.",
    "Sarah Palin.",
    "American Gladiators.",
    "Getting really high.",
    "Scientology.",
    "Penis envy.",
    "Praying the gay away.",
    "Frolicking.",
    "Two midgets shitting into a bucket.",
    "The KKK.",
    "Genghis Khan.",
    "Crystal meth.",
    "Serfdom.",
    "Stranger danger.",
    "A Bop It.",
    "Shaquille O'Neal's acting career.",
    "Prancing.",
    "Vigilante justice.",
    "Overcompensation.",
    "Pixelated bukkake.",
    "A lifetime of sadness.",
    "Racism.",
    "Dwarf tossing.",
    "Sunshine and rainbows.",
    "A monkey smoking a cigar.",
    "Flash flooding.",
    "Lance Armstrong's missing testicle.",
    "Dry heaving.",
    "The terrorists.",
    "Britney Spears at 55.",
    "Attitude.",
    "Breaking out into song and dance.",
    "Leprosy.",
    "Gloryholes.",
    "Nipple blades.",
    "The heart of a child.",
    "Puppies!",
    "Waking up half-naked in a Denny's parking lot.",
    "Dental dams.",
    "The taint; the grundle; the fleshy fun-bridge.",
    "Active listening.",
    "Ethnic cleansing.",
    "The Little Engine That Could.",
    "The invisible hand.",
    "Waiting 'til marriage.",
    "Unfathomable stupidity.",
    "Euphoria by Calvin Klein.",
    "Re-gifting.",
    "Autocannibalism.",
    "Erectile dysfunction.",
    "My collection of high-tech sex toys.",
    "The Pope.",
    "White people.",
    "Tentacle porn.",
#    "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.",
    "Too much hair gel.",
    "Seppuku.",
    "Same-sex ice dancing.",
    "Cheating in the Special Olympics.",
    "Charisma.",
    "Keanu Reeves.",
    "Sean Penn.",
    "Nickelback.",
    "A look-see.",
    "Pooping back and forth. Forever.",
    "Menstruation.",
    "Kids with ass cancer.",
    "A salty surprise.",
    "The South.",
    "The violation of our most basic human rights.",
    "YOU MUST CONSTRUCT ADDITIONAL PYLONS.",
    "Date rape.",
    "Being fabulous.",
    "Necrophilia.",
    "Centaurs.",
    "Bill Nye the Science Guy.",
    "Black people.",
    "Chivalry.",
    "Lunchables.",
    "Bitches.",
    "The profoundly handicapped.",
    "Heartwarming orphans.",
    "MechaHitler.",
    "Fiery poops.",
    "Another goddamn vampire movie.",
    "Tangled Slinkys.",
    "The true meaning of Christmas.",
    "Estrogen.",
    "A zesty breakfast burrito.",
    "That thing that electrocutes your abs.",
    "Passing a kidney stone.",
    "A bleached asshole.",
    "Michael Jackson.",
    "Cybernetic enhancements.",
    "Guys who don't call.",
    "Smallpox blankets.",
    "Masturbation.",
    "Classist undertones.",
    "Queefing.",
    "Concealing a boner.",
    "Edible underpants.",
    "Viagra.",
    "Soup that is too hot.",
    "Muhammad (Praise Be Unto Him).",
    "Surprise sex!",
    "Five-Dollar Footlongs.",
    "Drinking alone.",
    "Dick fingers.",
    "Multiple stab wounds.",
    "Soiling oneself.",
    "Child abuse.",
    "Anal beads.",
    "Civilian casualties.",
    "Pulling out.",
    "Robert Downey, Jr.",
    "Horse meat.",
    "A really cool hat.",
    "Kim Jong-il.",
    "A stray pube.",
    "Jewish fraternities.",
    "The token minority.",
    "Doin' it in the butt.",
    "Feeding Rosie O'Donnell.",
    "Teaching a robot to love.",
    "A can of whoop-ass.",
    "A windmill full of corpses.",
    "Count Chocula.",
    "Wearing underwear inside-out to avoid doing laundry.",
    "A death ray.",
    "The glass ceiling.",
    "A cooler full of organs.",
    "The American Dream.",
    "Keg stands.",
    "When you fart and a little bit comes out.",
    "Take-backsies.",
    "Dead babies.",
    "Foreskin.",
    "Saxophone solos.",
    "Italians.",
    "A fetus.",
    "Firing a rifle into the air while balls deep in a squealing hog.",
    "Dick Cheney.",
    "Amputees.",
    "Eugenics.",
    "My relationship status.",
    "Christopher Walken.",
    "Bees?",
    "Harry Potter erotica.",
    "College.",
    "Getting drunk on mouthwash.",
    "Nazis.",
    "8 oz. of sweet Mexican black-tar heroin.",
    "Stephen Hawking talking dirty.",
    "Dead parents.",
    "Object permanence.",
    "Opposable thumbs.",
    "Racially-biased SAT questions.",
    "Jibber-jabber.",
    "Chainsaws for hands.",
    "Nicolas Cage.",
    "Child beauty pageants.",
    "Explosions.",
    "Sniffing glue.",
#    "Glenn Beck being harried by a swarm of buzzards.",
    "Repression.",
    "Roofies.",
    "My vagina.",
    "Assless chaps.",
    "A murder most foul.",
    "Giving 110 percent.",
    "Her Royal Highness, Queen Elizabeth II.",
    "The Trail of Tears.",
    "Being marginalized.",
    "Goblins.",
    "Hope.",
    "The Rev. Dr. Martin Luther King, Jr.",
    "A micropenis.",
    "My soul.",
    "A hot mess.",
    "Vikings.",
    "Hot people.",
    "Seduction.",
    "An Oedipus complex.",
    "Geese.",
    "Global warming.",
    "New Age music.",
    "Hot Pockets.",
    "Making a pouty face.",
    "Vehicular manslaughter.",
    "Women's suffrage.",
    "A defective condom.",
    "Judge Judy.",
    "African children.",
    "The Virginia Tech Massacre.",
    "Barack Obama.",
    "Asians who aren't good at math.",
    "Elderly Japanese men.",
    "Exchanging pleasantries.",
    "Heteronormativity.",
    "Parting the Red Sea.",
    "Arnold Schwarzenegger.",
    "Road head.",
    "Spectacular abs.",
    "Figgy pudding.",
    "A mopey zoo lion.",
    "A bag of magic beans.",
    "Poor life choices.",
    "My sex life.",
    "Auschwitz.",
    "A snapping turtle biting the tip of your penis.",
    "A thermonuclear detonation.",
    "The clitoris.",
    "The Big Bang.",
    "Land mines.",
    "Friends who eat all the snacks.",
    "Goats eating cans.",
    "The Dance of the Sugar Plum Fairy.",
    "Jerking off into a pool of children's tears.",
    "Man meat.",
    "Me time.",
    "The Underground Railroad.",
    "Poorly-timed Holocaust jokes.",
    "A sea of troubles.",
    "Lumberjack fantasies.",
    "Morgan Freeman's voice.",
    "Women in yogurt commercials.",
    "Natural male enhancement.",
    "Being a motherfucking sorcerer.",
    "Genital piercings.",
    "Passable transvestites.",
    "Sexy pillow fights.",
    "Balls.",
    "Grandma.",
    "Friction.",
    "Party poopers.",
    "Farting and walking away.",
    "Being a dick to children.",
    "Booby-trapping the house to foil burglars.",
    "The Tempur-Pedic Swedish Sleep System.",
    "Dying.",
    "Hurricane Katrina.",
    "The gays.",
    "The folly of man.",
    "Men.",
    "The Amish.",
    "Pterodactyl eggs.",
    "Team-building exercises.",
    "A brain tumor.",
    "Cards Against Humanity.",
    "Fear itself.",
    "Lady Gaga.",
    "The milk man.",
    "A foul mouth.",
    "A big black dick.",
    "A beached whale.",
    "A bloody pacifier.",
    "A crappy little hand.",
    "A low standard of living.",
    "A nuanced critique.",
    "Panty raids.",
    "A passionate Latino lover.",
    "A rival dojo.",
    "A web of lies.",
    "A woman scorned.",
    "Clams.",
    "Apologizing.",
    "Appreciative snapping.",
    "Neil Patrick Harris.",
    "Beating your wives.",
    "Being a dinosaur.",
    "Shaft.",
    "Bosnian chicken farmers.",
    "Nubile slave boys.",
    "Carnies.",
    "Coughing into a vagina.",
    "Suicidal thoughts.",
    "Dancing with a broom.",
    "Deflowering the princess.",
    "Dorito breath.",
    "Eating an albino.",
    "Enormous Scandinavian women.",
    "Fabricating statistics.",
    "Finding a skeleton.",
    "Gandalf.",
    "Genetically engineered super-soldiers.",
    "George Clooney's musk.",
    "Getting abducted by Peter Pan.",
    "Getting in her pants, politely.",
    "Gladiatorial combat.",
    "Good grammar.",
    "Hipsters.",
    "Historical revisionism.",
    "Insatiable bloodlust.",
    "Jafar.",
    "Jean-Claude Van Damme.",
    "Just the tip.",
    "Mad hacky-sack skills.",
    "Leveling up.",
    "Literally eating shit.",
    "Making the penises kiss.",
    "Media coverage.",
    "Medieval Times Dinner and Tournament.",
    "Moral ambiguity.",
    "My machete.",
    "One thousand Slim Jims.",
    "Ominous background music.",
    "Overpowering your father.",
    "Pistol-whipping a hostage.",
    "Quiche.",
    "Quivering jowls.",
    "Revenge fucking.",
    "Ripping into a man's chest and pulling out his still-beating heart.",
    "Ryan Gosling riding in on a white horse.",
    "Santa Claus.",
    "Scrotum tickling.",
    "Sexual humiliation.",
    "Sexy Siamese twins.",
    "Slow motion.",
    "Space muffins.",
    "Statistically validated stereotypes.",
    "Sudden Poop Explosion Disease.",
    "The boners of the elderly.",
    "The economy.",
    "The Fanta girls.",
    "The Gulags.",
    "The harsh light of day.",
    "The hiccups.",
    "The shambling corpse of Larry King.",
    "The four arms of Vishnu.",
    "Being a busy adult with many important things to do.",
    "Tripping balls.",
    "Words, words, words.",
    "Zeus's sexual appetites.",
    "A beluga whale.",
    "Rambone.",
    "Illinois drivers.",
    "A delicious bag of Red Hot Riplets.",
    "The Mississippi River.",
    "Chesterfield.",
    "Provel cheese.",
    "The city/county debate.",
    "An ass-five.",
    "DTbot.",
    "Lolita cosplay.",
    "Ted Drewes.",
    "Breadco.",
    "David Freese.",
    "Tony La Russa.",
    "Albert Pujols.",
    "Yadi.",
    "The Cubs.",
    "The Red Sox.",
    "The Stan Span.",
    "Calling highway 40 I-64.",
    "North County.",
    "Imo's pizza.",
    "Gooey butter cake.",
    "QuikTrip.",
    "Toasted ravioli.",
    "The Loop.",
    "The Arch.",
    "Forest Park.",
    "Fast Eddie's.",
    "Mike Matheny.",
    "Jim Edmonds.",
    "misspwn.",
    "DT",
    "Living in Fenton.",
    "Jenn's sex toy collection.",
    "Waking up in a bed at Delmar Gardens.",
    "Pappy's Barbeque.",
    "Asking 'Where did you go to high school?'",
    "Gambling on the boat.",
    "A Veiled Prophet Parade Queen.",
    "Finding out you've been cat-fished.",
    "Boobs of all shapes and sizes.",
    "rikkitikki's smokin' hot bod.",
    "Nut Butter.",
    "Leaving no bitches unswooned.",
    "Brawndo, the thirst mutilator.",
    "Bill Cosby seductively rubbing his nipples with puddin pops.",
    "Being hit by the toilet seat of a space station re-entering the atmosphere.",
    "Packs of scissors that you need scissors to open.",
    "Lumpy Space Princess.",
    "Young faces with braces.",
    "Liking big butts, and being unable to lie about it.",
    "Touching someone's genitalia in the caves at the City Museum.",
    "Pegging.",
    "A bigger, blacker dick.",
    "The mere concept of Applebee's.",
    "A sad fat dragon with no friends.",
    "Catastrophic urethral trauma.",
    "Hillary Clinton's death stare.",
    "Existing.",
    "A pinata full of scorpions.",
    "Mooing.",
    "Swiftly achieving orgasm.",
    "Daddy's belt.",
    "Double penetration.",
    "Weapons-grade plutonium.",
    "Some really fucked-up shit.",
    "Subduing a grizzly bear and making her your wife.",
    "Rising from the grave.",
    "The mixing of the races.",
    "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.",
    "Scrotal frostbite.",
    "All of this blood.",
    "Loki, the trickster god.",
    "Whining like a little bitch.",
    "Pumping out a baby every nine months.",
    "Tongue.",
    "Finding Waldo.",
    "Upgrading homeless people to mobile hotspots.",
    "Wearing an octopus for a hat.",
    "An unhinged ferris wheel rolling toward the sea.",
    "Living in a trashcan.",
    "The corporations.",
    "A magic hippie love cloud.",
    "Fuck Mountain.",
    "Survivor's guilt.",
    "Me.",
    "Getting hilariously gang-banged by the Blue Man Group.",
    "Jeff Goldblum.",
    "Making a friend.",
    "A soulful rendition of 'Ol' Man River.'",
    "Intimacy problems.",
    "A sweaty, panting leather daddy.",
    "Spring break!",
    "Being awesome at sex.",
    "Dining with cardboard cutouts of the cast of 'Friends.'",
    "Another shot of morphine.",
    "Beefin' over turf.",
    "A squadron of moles wearing aviator goggles.",
    "Bullshit.",
    "The Google.",
    "Pretty Pretty Princess Dress-Up Board Game.",
    "The new Radiohead album.",
    "An army of skeletons.",
    "A man in yoga pants with a ponytail and feather earrings.",
    "Mild autism.",
    "Nunchuck moves.",
    "Whipping a disobedient slave.",
    "An ether-soaked rag.",
    "A sweet spaceship.",
    "A 55-gallon drum of lube.",
    "Special musical guest, Cher.",
    "The human body.",
    "Boris the Soviet Love Hammer.",
    "The grey nutrient broth that sustains Mitt Romney.",
    "Tiny nipples.",
    "Power.",
    "Oncoming traffic.",
    "A dollop of sour cream.",
    "A slightly shittier parallel universe.",
    "My first kill.",
    "Graphic violence, adult language, and some sexual content.",
    "Fetal alcohol syndrome.",
    "The day the birds attacked.",
    "One Ring to rule them all.",
    "Grandpa's ashes.",
    "Basic human decency.",
    "A Burmese tiger pit.",
    "Death by Steven Seagal.",
    "The Interwebs.",
    "AOL trial CDs.",
    "That ass.",
    "Having sex on top of a pizza.",
    "Three months in the hole.",
    "Nothing.",
    "Indescribable loneliness.",
    "A botched circumcision.",
    "Shutting the fuck up.",
    "An ass disaster.",
    "The Land of Chocolate.",
    "The primal, ball-slapping sex your parents are having right now.",
    "All my friends dying.",
    "Slapping a racist old lady.",
    "A cat video so cute that your eyes roll back and your spine slides out of your anus.",
    "Putting an entire peanut butter and jelly sandwich into the VCR.",
    "A lamprey swimming up the toilet and latching onto your taint.",
    "Cock.",
    "Spending lots of money.",
    "Jumping out at people.",
    "A cop who is also a dog.",
    "Some douche with an acoustic guitar.",
    "A black male in his early 20s, last seen wearing a hoodie.",
    "Dying alone and in pain.",
    "Flying robots that kill people.",
    "Mufasa's death scene.",
    "Gay aliens.",
    "A greased-up Matthew McConaughey.",
    "Bill Clinton, naked on a bearskin rug with a saxophone.",
    "The way white people is.",
    "An unstoppable wave of fire ants.",
    "Demonic possession.",
    "Reverse cowgirl.",
    "Not contributing to society in any meaningful way.",
    "The Harlem Globetrotters.",
    "The Quesadilla Explosion Salad from Chili's.",
    "An all-midget production of Shakespeare's Richard III.",
    "Vomiting mid-blowjob.",
    "Actually getting shot, for real.",
    "Screaming like a maniac.",
    "My manservant, Claude.",
    "Not having sex.",
    "The moist, demanding chasm of his mouth.",
    "Having shotguns for legs.",
    "Vietnam flashbacks.",
    "Filling every orifice with butterscotch pudding.",
    "Letting everyone down.",
    "Running naked through a mall, pissing and shitting everywhere.",
    "Unlimited soup, salad, and breadsticks.",
    "A spontaneous conga line.",
    "Warm, velvety muppet sex.",
    "Crying into the pages of Sylvia Plath.",
    "A vagina that leads to another dimension.",
    "Self-flagellation.",
    "Velcro.",
    "Disco fever.",
    "The systematic destruction of an entire people and their way of life.",
    "A PowerPoint presentation.",
    "Getting your dick stuck in a Chinese finger trap with another dick.",
    "Samuel L. Jackson.",
    "A surprising amount of hair.",
    "Fisting.",
    "A boo-boo.",
    "Eating Tom Selleck's mustache to gain his powers.",
    "The thin veneer of situational causality that underlies porn.",
    "Going around punching people.",
    "Girls that always be textin'.",
    "The entire Internet.",
    "A pile of squirming bodies.",
    "Blowing some dudes in an alley.",
    "Some kind of bird- man.",
    "Buying the right pants to be cool.",
    "Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy.",
    "Chugging a lava lamp.",
    "Blood farts.",
    "Sneezing, farting, and coming at the same time.",
    "A bunch of idiots playing a card game instead of interacting like normal humans.",
    "A sex goblin with a carnival penis.",
    "Lots and lots of abortions.",
    "Injecting speed into one arm and horse tranquilizer into the other.",
    "Sharks with legs.",
    "A sex comet from Neptune that plunges the Earth into eternal sexiness.",
    "How awesome I am.",
    "Smoking crack, for instance.",
    "A dance move that's just sex.",
    "Drinking responsibly.",
    "A hopeless amount of spiders.",
    "Bouncing up and down.",
    "Angelheaded hipsters burning for the ancient heavenly connection to the starry dynamo in the machinery of the night.",
    "A shiny rock that proves I love you.",
    "Crazy opium eyes.",
    "Finally finishing off the Indians.",
    "Moderate-to-severe joint pain.",
    "Actual mutants with medical conditions and no superpowers.",
    "The complex geopolitical quagmire that is the Middle East.",
    "Neil Diamond's Greatest Hits.",
    "No clothes on, penis in vagina.",
    "Whispering all sexy.",
    "A horse with no legs.",
    "Depression.",
    "Almost giving money to a homeless person.",
    "Interspecies marriage.",
    "Blackula.",
    "What Jesus would do.",
    "A manhole.",
    "My dad's dumb fucking face.",
    "A Ugandan warlord.",
    "My worthless son.",
    "A Native American who solves crimes by going into the spirit world.",
    "A kiss on the lips.",
    "A fart.",
    "The peaceful and nonthreatening rise of China.",
    "Snorting coke off a clown's boner.",
    "Three consecutive seconds of happiness.",
    "Falling into the toilet.",
    "Ass to mouth.",
    "Some sort of Asian.",
    "The size of my penis.",
    "The safe word.",
    "Party Mexicans.",
    "Ambiguous sarcasm.",
    "Jizz.",
    "An interracial handshake.",
    "10 Incredible Facts About the Anus.",
    "The secret formula for ultimate female satisfaction.",
    "Sugar madness.",
    "Calculating every mannerism so as not to suggest homosexuality.",
    "Fucking a corpse back to life.",
    "All the single ladies.",
    "Africa.",
    "Whatever a McRib is made of.",
    "Khakis.",
    "The euphoric rush of strangling a drifter.",
    "Stuffing a child's face with Fun Dip until he starts having fun.",
    "A gender identity that can only be conveyed through slam poetry.",
    "The tiniest shred of evidence that God is real.",
    "A for-real lizard that spits blood from its eyes.",
    "Prince Ali, fabulous he, Ali Ababwa.",
    "Dem titties.",
    "Exploding pigeons.",
    "My sex dungeon.",
    "Doo-doo.",
    "Child Protective Services.",
    "Sports.",
    "Unquestioning obedience.",
    "Grammar nazis who are also regular Nazis.",
    "Joe Buck's massive forehead.",
    "Pretending the metro east doesn't exist.",
    "New Town St. Charles.",
    "Being from Jefferson County.",
    "Puppy mills.",
    "Tom Shane's dull voice.",
    "Thinking Shane Co is a local business.",
    "Blow-up doll incest.",
    "A moustachioed car full of hipsters.",
    "A mysterious stain in the back of a cab.",
    "A terrible hand of CAH cards.",
    "Drinking negative beers.",
    "A moustache ride from Lyft.",
    "An Indian rope burn.",
    "A poopsack.",
    "Snail trails.",
    "A suspicious cupcake.",
    "Disposing of a body.",
    "Hookers and blow.",
    "Resting Bitch Face.",
    "Omega037.",
    "A ginger beard.",
    "A timely deflection.",
    "A potato dressed as a boy pretending to be a man.",
    "Shipping Evin and frisv.",
    "Feeling inspired by Hitler.",
    "Fighting sarcasm with more sarcasm.",
    "The Muny.",
    "Being Illinnoying.",
    "Constantly talking about living in Japan.",
    "Fruit Stripe Gum.",
    "A neckbeard tipping his fedora.",
    "A Men's Rights Activist.",
    "A Pick Up Artist.",
    "/r/theredpill",
    "Setting a QuikTrip on fire.",
    "Putting bacon in everything.",
    "Giving a running play-by-play of your night out.",
    "The Gay of the Day.",
    "A gay robot.",
    "Groot.",
    "grobend's semi-flaccid penis.",
    "The Stig.",
    "Jeremy Clarkson.",
    "A gentleman's sausage.",
    "Gentleman's relish.",
    "bk.",
    "bbbeluga.",
    "nerddtvg.",
    "GreetingsADM.",
    "spif.",
    "monkers.",
    "rikkitikki.",
    "Peeing in a girl's butt.",
    "Big Dick Problems.",
    "A wink from Primesauce.",
    "Ms. New Booty.",
    "The Players' Club.",
    "Whips and chains.",
    "A sex swing.",
    "A steam-powered fucking machine.",
    "A girl dressed as a pinata.",
    "A hands-free blowjob.",
    "Calming your tits.",
    "secretninjaket's rack.",
#    "Mr. Rogers balls deep in an underage prostitute.",
    "A gum-job from Grandma.",
    "Getting dust in your hoo-hah.",
    "Poop bang.",
    "Breakfast at the Cracker Barrel.",
    "A shitty suggestion for a new card.",
    "Fucklings.",
    "Pumpkin spice flavored condoms.",
    "Literally sleeping with the fishes.",
    "k27463 cosplaying as Thomas the Tank Engine.",
    "A Pomplamoose show.",
    "Gluing pubes to my face in lieu of growing a beard.",
    "Forgetting about Primus.",
    "Forgetting about Dre.",
    "Two trailer park girls going 'round the outside.",
    "Big money, no whammies.",
    "A dildo made of frozen HIV.",
    "Getting 9/10 in a trivia category you suggested.",
    "Naming everything after poop.",
    "Having a million friends but not really knowing anybody.",
    "Being part of the 1%.",
    "Joining an unpopular movement.",
    "A tree falling silently in an empty forest.",
    "#GamerGate",
    "The Boobseum",
    "Peeing in Forest Park.",
    "tadni.",
    "A new technique for peeing while driving.",
    "Nerfdude.",
    "Showing up at someone's workplace unannounced and calling it a meetup.",
    "Turning around in bk's driveway.",
    "Too Many Cooks.",
    "Too Many Cocks.",
    "Creating a reference experience for the spank bank.",
    "Three grandmas trying marijuana for the first time.",
    "Hamster-sized snowflakes.",
    "Electropop.",
    "ajwalsh44.",
    "||cw.",
    "zeryl.",
    "Electropop's virginity.",
    "Inappropriate use of Comic Sans.",
    "anotherbofh.",
    "Weaponized whales with shotgun blowholes.",
    "Your mom.",
    "An incessantly whistling co-worker.",
    "Afterbirth.",
    "A five-drink lesbian.",
    "Listless testicles.",
    "Overpriced, overrated, and oversalted roast beef.",
    "_Deity.",
    "Gary Busey's crazy fucking face.",
    "rikkitikki's non-smokin' area of the restaurant.",
    "Having a penis.",
    "A sexually suggestive name.",
    "A properly inflated ball.",
    "Well-manicured pubic hair.",
    "Candy cane jizz.",
    "Getting fucked by a boron dildo.",
    "Cold dicks.",
    "Rotwang.",
    "A St. Louis coal torpedo.",
    "kitkatkaytee.",
    "scittles.",
    "Cis-scum.",
    "Marlon Brando.",
    "The Godfather.",
    "Butts.",
    "Butt stuff.",
    "Failing to live up to your parents' legacy.",
    "A Brazilian from a Brazilian.",
    "Ketchup on a cracker.",
    "OPP.",
    "Semen-flavored candy.",
    "A greasy banana.",
    "A social justice warrior.",
    "The Crusty Puffins.",
    "Chank.",
    "NefariousAMG.",
    "Going to a different trivia night.",
    "A trigger warning.",
    "Demanding that a card be removed.",
    "A legitimate Ecuadorian.",
    "NefariousAMG.",
    "Being on-call for sex.",
    "sushiiii.",
    "Chewbaccer.",
    "mdchap.",
    "Trains.",
    "HO scale.",
    "Robbles.",
#Crabs
    "A $50 cup of coffee literally made from cat shit.",
    "A beard longer than 12 inches.",
    "A four-inch clit.",
    "A hamster with a throbbing erection.",
    "A mazel tov cocktail.",
    "A nugget of poo roughly the size and shape of a crouton.",
    "A prehensile penis.",
    "A sexually aggressive koala.",
    "A shockingly flatulent bobcat.",
    "A strong, independent woman who don't need no man.",
    "A tossed salad.",
    "An asexual bonobo.",
    "An entire bottle of Jagermeister.",
    "An extra-large can of Bone Bashful brand Chinchilla Pudding Sauce.",
    "An Oosik, or Inuit war club made from the penis bone of a walrus.",
    "An overly-enthusiastic prostate exam.",
    "An unsurprising rash.",
    "Axl Rose.",
    "Bacon that can feel pain.",
    "Bacon-flavored lube",
    "Being born with a tail.",
    "Being kicked in the ovaries.",
    "Being punk in drublic.",
    "Being raped to sleep by dickwolves.",
    "Belching out the lyrics to 'Hey Jude'.",
    "Bono. Just... Bono.",
    "Bronies.",
    "Cockasaurus rex: the horniest dinosaur of them all.",
    "Cocktimus Prime: the laser-guided dildo rocket.",
    "Costco food samples.",
    "Death by snu-snu.",
    "Droppin' the mic.",
    "Enrolling in clown school.",
    "Erotic balloon animals.",
    "Explaining how I got the nickname 'Nibbleberries'.",
    "Ezekiel 23:20 'There she lusted after her lovers, whose genitals were like those of donkeys and whose emission was like that of horses.'",
    "Flop sweat.",
    "Gilbert Gottfried's voice.",
    "Giving Anne Frank a drum kit for her birthday.",
    "Giving the tumor a cutesy name.",
    "Googling 'Betty White nude'.",
    "Grandma's wet, sloppy kisses.",
    "Honey Boo Boo shotgunning a 2-liter bottle of 'go-go juice'.",
    "Insisting that Jesus is technically a zombie.",
    "JJ Abrams putting lens flares all over everything.",
    "Joe Biden getting his freak on.",
    "Joffrey Baratheon, the loathsome little shit.",
    "Lego recreations of famous porn scenes.",
    "Michele Bachmann furiously masturbating with a coathanger.",
    "Mitt Romney doing a burlesque routine in a giant champagne glass.",
    "Monkey torture.",
    "My level 90 night elf, Leafshit Puddingsbane.",
    "Natalie Portman naked, petrified, and covered in hot grits.",
    "Officially no longer giving a shit.",
    "Plato's Allegory of the Cave or some other pretentious bullshit.",
    "Posting on /r/gonewild/.",
    "Pretending to be a malfunctioning robot.",
    "Pretending to have the hiccups.",
    "Pronouncing 'quinoa' properly.",
    "Racist ninjas.",
    "Raptor Jesus.",
    "Reluctant anal.",
    "S'more Schnapps.",
    "Selling out.",
    "Sexy witches.",
    "Slightly more than 3 ounces of cum.",
    "Steaming hot lemonade.",
    "Struggle snuggles.",
    "That 'not-so-fresh' feeling.",
    "The combined fat from all of the Kardashians' liposuction procedures.",
    "The fabled Mongolian Death Worm.",
    "The green apple splatters.",
    "The Slender Man.",
    "The TARDIS.",
    "Touching each other's butts.",
    "Using teeth.",
    "Van Gogh's severed ear.",
    "Weaponized ebola.",
    "Wielding a toddler as a weapon.",
    "WINNING!!",
    "Yoga pants.",
    "A 5 lb. bag of gummy bears.",
    "A bachelor's degree in communication.",
    "A bit o' the ol' slap and tickle.",
    "A bitchin' Camaro",
    "A blanket with a hole in it.",
    "A breakfast sausage with serious emotional problems.",
    "A chair that likes to rape people.",
    "A cunning stunt.",
    "A good schtupping.",
    "A gratuitous claymation sequence.",
    "A hairshirt.",
    "A husband bulge.",
    "A jury of your peers.",
    "A sense of resignation.",
    "A slack-jawed yokel.",
    "A stinky pinky.",
    "A tender rogering.",
    "A warm, gently fragrant biscuit.",
    "A were-salmon.",
    "A younger, vastly more attractive spouse.",
    "An angry little man.",
    "An effeminate southern homophobe.",
    "Applying to a new guild",
    "Barfing into a tiny, bejeweled handbag.",
    "Being able to name all of the different kinds of olives.",
    "Being circumcised with a deli slicer.",
    "Being small but perfectly well formed.",
    "Bitch tits.",
    "Blistering barnacles!",
    "Bourbon pong.",
    "Cockissimo Fantastico, the legendary lover with a wondrous wang.",
    "Cockulous Maximus, tremendous tallywacker of Tripoli.",
    "Gazpacho tactics.",
    "Giving your pet lamb a Brazilian.",
    "Hakuna matata, motherfucker.",
    "Her dry, scaly hands.",
    "Hooking up at a Tegan & Sarah concert.",
    "Japanese rope technique.",
    "Kentucky Fried Children.",
    "Killing hobos.",
    "Making vigorous love to a Taco Bell Beefy 5-Layer Burrito.",
    "Mesothelioma.",
    "Minimum wage.",
    "Mongolian 'beef'.",
    "Not being too smelly, you know, in the cellar. Down Below.",
    "One Direction.",
    "One whose nether regions are vast and backoning, like unto a corridor down which a frankfurther might be thrown.",
    "Opening for Sigur Ros.",
    "Painal.",
    "Paula Deen's dietitian.",
    "Poop soup.",
    "Pooping in public.",
    "Reptilians.",
    "Rich Corinthian leather.",
    "Rock bottom.",
    "Running around like a guy with his chicken cut off.",
    "Self-medicating.",
    "Self-replicating fudge.",
    "Slowly waving an oversized Jamaican flag.",
    "Something Elon Musk thought up while floating six inches above the floor in a meditative trance.",
    "Spiking the juice at AA.",
    "Sploosh!",
    "Swallowing a cue ball.",
    "Tacos.",
    "Ted Nugent's cold, dead hands.",
    "That thing with the spoon.",
    "The Cliterati.",
    "The creative use of a pool noodle.",
    "The smooth, unblemished skin of a child.",
    "The soft love-honks of a lusty goose.",
    "The whole goddamned thing.",
    "Those creamy atheist thighs.",
    "Titty sprinkles.",
    "Tufted ears.",
    "Uncontrollably retching at the mere mention of mayonnaise.",
    "Using a zip-tie as an impromptu cock-ring.",
    "Using tears as lubricant.",
    "Wearing a blue fox fursuit on Casual Friday.",
    "Wearing your IUD into an MRI.",
#KwanzaaPast
    "A protracted siege.",
    "200 years of slavery.",
    "Harnessing the miraculous power of the atom to slaughter 200,000 Japanese people.",
    "Rock music and premarital sex.",
    "This groovy new thing called LSD.",
    "Blockbuster late fees up the wazoo.",
    "The Bowflex Revolution.",
    "Reading an entire book.",
#KwanzaaPresent
    "All the poop inside my body.",
    "A vague fear of something called ISIS.",
    "The diminishing purity of the white race.",
    "Ebola.",
    "Trying to feel something, anything.",
    "Small-town cops with M4 assault rifles.",
    "The 9000 children who starved to death today.",
    "The transience of all things.",
#KwanzaaFuture
    "What remains of my penis.",
    "Rising sea levels consistent with scientific predictions.",
    "Being replaced by a robot.",
    "The events depicted in James Cameron's Avatar.",
    "Building a ladder of hot dogs to the moon.",
    "The Great Lizard Uprising of 2352.",
    "A cloud of ash that darkens the Earth for a thousand years.",
    "The dying breath of the last human.",
]

def bcards():
    return [
    "TSA guidelines now prohibit __________ on airplanes.",
    "It's a pity that kids these days are all getting involved with __________.",
    "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.",
    "Major League Baseball has banned __________ for giving players an unfair advantage.",
    "What is Batman's guilty pleasure?",
    "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
    "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
    "What did I bring back from Mexico?",
    "__________? There's an app for that.",
    "__________. Betcha can't have just one!",
    "What's my anti-drug?",
    "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time. ",
    "What's my secret power?",
    "What's the new fad diet?",
    "What did Vin Diesel eat for dinner?",
    "When Pharaoh remained unmoved, Moses called down a Plague of __________.",
    "How am I maintaining my relationship status?",
    "In the St Louis County Jail, word is you can trade 200 cigarettes for __________.",
    "After the earthquake, Sean Penn brought __________ to the people of Haiti.",
    "Instead of coal, Santa now gives the bad children __________.",
    "Life for American Indians was forever changed when the White Man introduced them to __________.",
    "What's Teach for America using to inspire inner city students to succeed?",
    "Maybe she's born with it. Maybe it's __________.",
    "In Michael Jackson's final moments, he thought about __________.",
    "White people like __________.",
    "Why do I hurt all over?",
    "A romantic, candlelit dinner would be incomplete without __________.",
    "What will I bring back in time to convince people that I am a powerful wizard?",
    "BILLY MAYS HERE FOR __________.",
    "The class field trip was completely ruined by __________.",
    "What's a girl's best friend?",
    "Dear Abby, I'm having some trouble with __________ and would like your advice.",
    "When I am President of the United States, I will create the Department of __________.",
    "What are my parents hiding from me?",
    "What never fails to liven up the party?",
    "What gets better with age?",
    "__________: Good to the last drop.",
    "I got 99 problems but __________ ain't one.",
    "__________. It's a trap!",
    "MTV's new reality show features eight washed-up celebrities living with __________.",
    "What would grandma find disturbing, yet oddly charming?",
    "During sex, I like to think about __________.",
    "What ended my last relationship?",
    "What's that sound?",
    "__________. That's how I want to die.",
    "Why am I sticky?",
    "What's the next Happy Meal toy?",
    "What's there a ton of in heaven?",
    "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.",
    "What will always get you laid?",
    "__________: Kid-tested, mother-approved.",
    "Why can't I sleep at night?",
    "What's that smell?",
    "What helps Obama unwind?",
    "This is the way the world ends / This is the way the world ends / Not with a bang but with __________.",
    "Coming to Broadway this season, __________: The Musical.",
    "Anthropologists have recently discovered a primitive tribe that worships __________.",
#    "But before I kill you, Mr. Bond, I must show you __________.",
    "Studies show that lab rats navigate mazes 50% faster after being exposed to __________.",
    "Next on ESPN2: The World Series of __________.",
    "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.",
    "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________.",
    "War! What is it good for?",
    "What gives me uncontrollable gas?",
    "What do old people smell like?",
    "What am I giving up for Lent?",
    "Alternative medicine is now embracing the curative powers of __________.",
    "What did the US airdrop to the children of Afghanistan?",
    "What does Dick Cheney prefer?",
    "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________.",
    "What don't you want to find in your Chinese food?",
    "I drink to forget __________.",
    "__________. High five, bro.",
    "He who controls __________ controls the world.",
    "The CIA now interrogates enemy agents by repeatedly subjecting them to __________.",
    "In Rome, there are whisperings that the Vatican has a secret room devoted to __________.",
    "Science will never explain the origin of __________.",
    "When all else fails, I can always masturbate to __________.",
    "I learned the hard way that you can't cheer up a grieving friend with __________.",
    "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated __________.",
    "The socialist governments of Scandinavia have declared that access to __________ is a basic human right.",
    "In his new self-produced album, Kanye West raps over the sounds of __________.",
    "What's the gift that keeps on giving?",
    "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only __________ and his wits. ",
    "When I pooped, what came out of my butt?",
    "In the distant future, historians will agree that __________ marked the beginning of America's decline.",
    "What has been making life difficult at the nudist colony?",
    "And I would have gotten away with it, too, if it hadn't been for __________.",
    "What brought the orgy to a grinding halt?",
    "When I went to college I majored in __________.",
    "Instead of merging with St Louis County, the city will merge with __________.",
    "The next big event moving to Chesterfield is __________.",
    "The new seasonal brew from Schlafly is called __________.",
    "It's not the heat, it's __________.",
    "The newest stranger creation at Strange Donuts is called __________.",
    "St. Charles County residents will never allow a Metrolink extension, for fear of __________.",
    "If you don't like __________, wait 5 minutes.",
    "Meet me at __________!",
    "The new Ballpark Village dress code prohibits __________.",
    "__________. Not even once.",
    "__________ is now 10 for $10 at Schnucks.",
    "One of the goats at Grant's Farm tried to eat __________.",
    "The only thing St Louis wants more than an IKEA is __________.",
    "I don't pee in a girl's butt unless I'm __________! Because I'm a fucking gentleman!",
    "The weird kids from high school never stop being weird, we just get better at __________.",
    "What is the Ultimate Answer of Life, The Universe and Everything?",
    "My new favorite subreddit is r/__________.",
    "TONY STARK BUILT __________ IN A CAVE! WITH A BOX OF SCRAPS!!!",
    "How crazy would that be, you are about get it on with someone, pull off their shirt and BLAM __________.",
    "What is the Hokey-pokey really all about?",
    "If __________ were an Olympic Sport, I'd win the gold medal.",
    "You know Nintendo is running out of ideas when they base a new Pokemon on __________.",
    "You know how I know you're gay? You like __________.",
    "Thanks to autocorrect, I sent my boss a text telling them I would be busy working on __________ this weekend.",
    "During his midlife crisis, my dad got really into __________.",
    "My new favorite porn star is Joey '__________' McGee.",
    "Before I run for president, I must destroy all evidence of my involvement with __________.",
    "This is your captain speaking. Fasten your seatbelts and prepare for __________.",
    "In his newest and most difficult stunt, David Blaine must escape from __________.",
    "The Five Stages of Grief: denial, anger, bargaining, __________, and acceptance.",
    "Members of New York's social elite are paying thousands of dollars just to experience __________.",
    "This month's Cosmo: 'Spice up your sex life by bringing __________ into the bedroom.'",
    "Little Miss Muffet Sat on a tuffet, Eating her curds and __________.",
    "My country, 'tis of thee, sweet land of __________.",
    "After months of debate, the Occupy Wall Street General Assembly could only agree on 'More __________!'",
    "Next time on Dr. Phil: How to talk to your child about __________.",
    "Only two things in life are certain: death and __________.",
    "Everyone down on the ground! We don't want to hurt anyone. We're just here for __________.",
    "The healing process began when I joined a support group for victims of __________.",
    "The votes are in, and the new high school mascot is __________.",
    "Charades was ruined for me forever when my mom had to act out __________.",
    "Tonight on 20/20: What you don't know about __________ could kill you.",
    "I'm the Batman of __________.",
    "I'm the Michael Jordan of __________.",
    "In the seventh circle of Hell, sinners must endure __________ for all eternity.",
    "Call the law offices of Goldstein & Goldstein, because no one should have to tolerate __________ in the workplace.",
    "A successful job interview begins with a firm handshake and ends with __________.",
    "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of __________.",
    "Lovin' you is easy 'cause you're __________.",
    "Turns out that __________-Man was neither the hero we needed nor wanted.",
    "Finally! A service that delivers __________ right to your door.",
    "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for __________.",
    "My gym teacher got fired for adding __________ to the obstacle course.",
    "The blind date was going horribly until we discovered our shared interest in __________.",
    "Money can't buy me love, but it can buy me __________.",
    "__________. Awesome in theory, kind of a mess in practice.",
    "As part of his contract, Prince won't perform without __________ in his dressing room.",
    "I'm not like the rest of you. I'm too rich and busy for __________.",
    "And what did you bring for show and tell?",
    "During high school I never really fit in until I found __________ club.",
    "What left this stain on my couch?",
    "Hey baby, come back to my place and I'll show you __________.",
    "The meek shall inherit __________.",
    "What's fun until it gets weird?",
    "Wes Anderson's new film tells the story of a precocious child coming to terms with __________.",
    "I'm sorry, sir, but we don't allow __________ at the country club.",
    "How am I compensating for my tiny penis?",
    "You've seen the bearded lady! You've seen the ring of fire! Now, ladies and gentlemen, feast your eyes upon __________!",
    "She's up all night for good fun. I'm up all night for __________.",
    "Dear Leader Kim Jong-un, our village praises your infinite wisdom with a humble offering of __________.",
    "Man, this is bullshit. Fuck __________!",
    "The Japanese have developed a smaller, more efficient version of __________.",
    "Alright, bros. Our frat house is condemned, and all the hot slampieces are over at Gamma Phi. The time has come to commence Operation __________.",
    "This is the prime of my life. I'm young, hot, and full of __________.",
    "I'm pretty sure I'm high right now, because I'm absolutely mesmerized by __________.",
    "It lurks in the night. It hungers for flesh. This summer, no one is safe from __________.",
    "Do not fuck with me! I am literally __________ right now.",
    "2 AM in the city that never sleeps. The door swings open and she walks in, legs up to here. Something in her eyes tells me she's looking for __________.",
    "As king, how will I keep the peasants in line?",
    "Carol House Furniture: because you like __________.",
    "Now you have a friend in the __________ business!",
    "The square beyond __________!",
    "A judge has issued a restraining order against a startup bringing __________ to the people of St Louis.",
    "__________. THANKS OBAMA",
    "What's the theme for rikkitikki's newest outfit?",
    "We can't take misspwn anywhere because she likes __________.",
    "What's bbbeluga excited about?",
    "The first thing people usually notice about me is __________.",
    "I'm really good at __________.",
    "bk had to rewrite part of the CAH bot because of __________.",
    "GreetingsADM got his nickname from __________.",
    "Chank is marked 'gone' because of __________.",
    "nerddtvg got upset because nobody thought __________ was funny.",
    "If it weren't for __________, I wouldn't have spent that year in college.",
    "Why does Charles 'Ed' Brown, attorney at law, have to wear an eye patch?",
    "Lemmons had to close because the owner was sick of __________.",
    "What caused the citizens of North County to riot?",
    "At the trade deadline, the Cardinals announced their new secret weapon: __________.",
    "St Louis County Police were heavily criticized for their use of __________.",
    "What does spif find too offensive to handle?",
    "Once again, tadni is complaining because of his sister's involvement with __________.",
    "The latest awareness campaign stunt involves __________.",
    "Top Gear's Jeremy Clarkson recently got blasted by the papers for his comments on __________.",
    "Open the door, get on the floor. Everybody walk __________.",
    "The latest addition to k27463's model train setup is __________.",
    "Because zeryl lives in Troy, he can't enjoy __________ with the rest of us.",
    "What did I get instead of a beer when I gave DTbot a high five?",
    "What's the latest feature to be added to DLbot?",
    "If ||cw got more involved with __________, there would definitely be a card written about him.",
    "dolemite7 is looking for a unicode emoticon that successfully communicates the feeling of __________.",
    "Charter experienced a nationwide service interruption because of __________.",
    "What is always DeliriumTremens' fault?",
    "What's TenthTARDIS most looking forward to in the new series of Doctor Who?",
    "Primesauce identifies as a cloud because of __________.",
    "The Rams are finally moving to LA after a disappointing performance against __________.",
    "How is babby formed? How girl get pragnent?",
    "Booty booty booty booty rockin' __________.",
    "For my New Year's resolution, I'm planning on improving __________.",
    "We, the people of the United States, in order to form a more perfect union, [...] do ordain and establish __________.",
    "What's secretninjaket's secret?",
    "Evin gave up the glamorous life of a journalist in order to pursue __________.",
    "Would you be mine? Could you be mine? Won't you be __________?",
    "I lost my faith in God when I learned about __________.",
    "I like __________ and I cannot lie.",
    "You can tell it's a new season because all the stores are selling __________.",
    "What's the newest product to be offered in pumpkin spice flavor?",
    "Today is National __________ Day!",
    "Chank and bk can't stop fighting about __________.",
    "What name will the trivia team use this week?",
    "Anything, including __________, can be a dildo if you're brave enough.",
    "spif has a friend that's familiar with __________.",
    "__________ is a lie.",
    "I got a creepy message asking for pics of __________.",
    "More people die each year from __________ than from Ebola.",
    "Why did I get sent home from school?",
    "Actually, it's not about __________, it's about ethics in journalism.",
    "For Halloween I'm dressing up as a slutty version of __________.",
    "Casino QueeEEEeen, home of __________!",
    "Why did I have to register as a sex offender?",
    "What was Nerfdude's favorite experience on his recent trip to Japan?",
    "__________? That shit cray.",
    "What is Electropop saving herself for?",
    "* anotherbofh is now known as bofh|__________.",
    "What is _Deity ranting about today?",
    "One day Nyghtshade will be old enough for __________.",
    "I can't play CAH right now because I have to pay attention to __________.",
    "The sequel to 50 Shades of Grey will be called 50 Shades of __________.",
    "If I want my friends to think I'm cool I tell them stories about __________.",
    "scittles' favorite thing to buy from ALDI is __________.",
    "According to anotherbofh, the answer to every trivia question is __________.",
    "St Louis area residents freaked out when the tornado sirens went off, but it turns out it was just __________.",
    "If you can't say something nice about __________, don't say anything at all.",
    "Electropop's least favorite college class focused on __________.",
    "You down with __________? Yeah, you know me.",
    "Because he doesn't drink, k27463 is more interested in __________ than attending most /r/stl meetups.",
    "TRIGGER WARNING: __________.",
    "secretninjaket just found out she's allergic to __________.",
    "ajwalsh44 isn't famous murder victim Adam Walsh; he's actually __________.",
    "What does Chewbaccer miss most about Pennsylvania?",
    "mdchap was born in 1990, the same year __________ debuted.",
    "Because his email address contained __________, k27463 was stuck with being called that at work forever.",
#Crabs
    "__________: Just sayin'.",
    "__________: not even once.",
    "According to a new UN treaty, __________ now qualifies as a weapon of mass destruction.",
    "Ever since 'the incident', every time I close my eyes, I still see __________.",
    "Gentlemen, I'm sure you're wondering why I asked you here this evening. It's a long story, but it all began with __________.",
    "How did I get this restraining order?",
    "How did I hurt my back?",
    "How did my grandparents make it through the Great Depression?",
    "I am become __________, destroyer of worlds.",
    "I'm so hungry I could eat __________.",
    "If you want a picture of the future, imagine a boot stamping on __________--forever.",
    "In a move that has Hollywood insiders baffled, the producers of American Idol have decided to replace host Ryan Seacrest with __________.",
    "In my opinion, __________ is grounds for justifiable homicide.",
    "It took seven years in a remote Tibetan monastery, but I finally learned the art of __________.",
    "Like Midas reborn, everything she touches turns to __________.",
    "Oh my God! They killed __________! You bastards!",
    "The best part of waking up is __________.",
    "Tonight on 'My Super Sweet 16', Stephani's parents give her __________.",
    "What was one of the rejected flavors for Baskin-Robbins ice cream?",
    "Why won't they let me in Chuck E. Cheese's anymore?",
    "William Shatner's shocking new autobiography is titled '__________: The Final Frontier'.",
    "__________: it's magically delicious.",
    "__________? That's what she said.",
    "'You have my sword.' 'And you have my bow.' 'And my __________!'",
    "A new Russian dash-cam video shows __________, right there in the middle of the street!",
    "Apple has announced a new device that promises to revolutionize the way we think about __________.",
    "Audiences at Sundance were traumatized by Lars von Trier's controversial new film, '__________'.",
    "Dear Dan Savage, Please help. I am unable to achieve orgasm without __________.",
    "Experts say that without careful management and conservation, __________ will disappear within our lifetimes.",
    "From the people who brough you Sharktopus and Sharknado, Syfy's next horror film combines sharks with __________.",
    "Having abandoned his pleas for a return to the gold standard, Ron Paul is now promoting a __________-based economy.",
    "What's the name of my latest music project?",
    "I don't care what people say, __________ is not a crime.",
    "I have to admit... it took me a while to agree to it, but incorporating __________ into our wedding ceremony is a decision I will never regret.",
    "I quit my job as a bartender the night some jackass left me __________ as a tip.",
    "I think I need to take Fluffums to puppy training---he has this terrible habit of __________.",
    "I wish it were something simple, like peanuts or shellfish, but my doctor tells me I'm actually allergic to __________.",
    "If people wouldn't be so quick to judge, I would give __________ to anyone in this channel in a heartbeat.",
    "Michelle Obama outraged conservatives when she implied that __________ maybe wasn't such a bad thing.",
    "My tour of the White House radically escalated when Secret Service caught a glimpse of __________ in my bag.",
    "Now that he has retired, Pope Benedict can finally devote time to his true passion: __________.",
    "Oh, so you think you're too good for us now, little miss '__________'!",
    "WANTED: a clean, well-lit place for __________.",
    "When you play the Game Of __________, you win or you die.",
    "Why won't anyone sit with me?",
#KwanzaaPast
    "Dear Mom and Dad, Camp is fun. I like capture the flag. Yesterday, one of the older kids taught me about __________. I love you, Casey.",
    "Honey, Mommy and Daddy love you very much. But apparently Mommy loves __________ more than she loves Daddy.",
#KwanzaaPresent
    "Why am I so tired?",
#KwanzaaFuture
    "Behold the Four Horsemen of the Apocalypse! War, Famine, Death, and __________.",
]

def bcards2():
    return [
    "That's right, I killed __________. How, you ask? __________.",
    "And the Academy Award for __________ goes to __________.",
    "For my next trick, I will pull __________ out of __________.",
    "In his new summer comedy, Rob Schneider is __________ trapped in the body of __________.",
    "When I was tripping on acid, __________ turned into __________.",
    "__________ is a slippery slope that leads to __________.",
    "In a world ravaged by __________, our only solace is __________.",
    "In M. Night Shyamalan's new movie, Bruce Willis discovers that __________ had really been __________ all along.",
    "I never truly understood __________ until I encountered __________.",
    "Rumor has it that Vladimir Putin's favorite dish is __________ stuffed with __________.",
    "Lifetime presents __________, the story of __________.",
    "What's the next superhero/sidekick duo?",
    "__________ and __________: Still a better love story than Twilight.",
    "Order __________ in the next 5 minutes and get __________ absolutely FREE!",
    "__________ would be woefully incomplete without __________.",
    "My mom freaked out when she looked at my browser history and found __________.com/__________.",
    "If God didn't want us to enjoy __________, he wouldn't have given us __________.",
    "I spent my whole life working toward __________, only to have it ruined by __________.",
    "Before __________, all we had was __________.",
    "You haven't truly lived until you've experienced __________ and __________ at the same time.",
    "I made you a mix tape with songs about your favorite things: __________ and __________.",
    "Listen, son. If you want to get involved with __________, I won't stop you. Just steer clear of __________.",
    "Having problems with __________? Try __________!",
    "With enough time and pressure, __________ will turn into __________.",
    "My life is ruled by a vicious cycle of __________ and __________.",
    "When you get right down to it, __________ is just __________.",
    "In the beginning, there was __________. And the Lord said, 'Let there be __________.'",
    "__________ will never be the same after __________.",
    "We never did find __________, but along the way we sure learned a lot about __________.",
    "__________ may pass, but __________ will last forever.",
    "In return for my soul, the Devil promised me __________, but all I got was __________.",
    "If you can't handle __________, you'd better stay away from __________.",
    "Forget everything you know about __________, because now we've supercharged it with __________!",
    "Honey, I have a new role-play I want to try tonight! You can be __________ and I'll be __________.",
    "This year's hottest album is '__________' by __________.",
    "Every step towards __________ gets me a little bit closer to __________.",
    "Oprah's book of the month is '__________ For __________: A Story of Hope.'",
    "Adventure. Romance. __________. From Paramount Pictures, '__________.'",
    "I am become __________, destroyer of __________!",
    "Great news! Because of our success with __________ we're going to have a department __________ party!",
    "__________: Hours of fun. Easy to use. Perfect for __________!",
    "After months of practice with __________, I think I'm finally ready for __________.",
    "What will the categories be for the next two rounds of trivia?",
    "Omega037 started an argument by suggesting that __________ and __________ were the same thing.",
    "monkers invited all the girls out for __________ and __________.",
    "__________ and __________? Too soon!",
    "The specials for today are __________ and __________.",
    "bk is working on a new song that incorporates __________ and __________.",
    "I can't wait for __________ and __________ to coincide. But not in real life. Just in the cards.",
    "My surefire pickup line involves asking about __________ and suggesting that we go back to my place for __________.",
    "If you squint your eyes just right, __________ looks just like __________.",
    "rikkitikki is sad she moved to San Diego because she'll miss out on __________ and __________.",
#crabs
    "A wild __________ appears! You used __________! It's super effective!", 
    "I was once sent to the HR department for an incident involving __________ and __________.",
    "I'm gonna go build my own theme park! With __________! And __________!",
    "PornHub.com's single most popular video features __________ and __________.", 
    "So then he says, 'If you want to make this relationship work, you need to give up __________ and __________.' As. If.",
    "Thanks to __________, I now have a crippling fear of __________.",
    "The last two items on my bucket list are __________ and __________.",  
    "When I'm dating somebody, I can overlook __________, but __________ is a deal-breaker.",
    "An ounce of __________ is worth a pound of __________.",
    "Bentley's latest ultra-high-end luxury sedan comes complete with __________ and __________.",
    "Dear, your father and I found __________ and __________ in your bedroom. I'm shocked, and frankly just a little disappointed.",
    "I got some strange looks in the checkout line when the cashier noticed __________ and __________ in my cart.",
    "Netflix's new original series is a sitcom based around __________ and __________.",
    "The NSA wants to talk to me about an email I sent out containing phrases like __________ and __________.",
    "When I've seriously fucked up and need to make amends, what can I give my significant other to show them I am truly remorseful?",
    "Yea, though I walk through the valley of __________, I will fear no __________.",
#KwanzaaPresent
    "Today on Buzzfeed: 10 pictures of __________ That Look Like __________!",
#KwanzaaFuture
    "A curse upon thee! Many years from now, just when you think you're safe, __________ shall turn into __________."
]
