sets.append("science")
wcards-science = [
    “Mouth Pipetting.”,
    “Repetitive stress injury.",
    “Computers older than the combined age of all grad students.",
    “The grad student who has been in the department longer than all known faculty.",
    “Asbestos.",
    “Golden boy.",
    “Bayesian statistics.",
    “The token female professor.",
    “That one female engineer everyone knows but is afraid to ask out.",
    “Labcest (lab incest).",
    “Ecologist chic.",
    “Gastrointestinal worms.",
    “Anthrax.",
    “Ernst Haeckel.",
    “The Lotka-Volterra Equation.",
    “J.B.S. Haldane.",
    “Island biogeography.",
    “Intermediate host.",
    “Schistosomiasis.",
    “Rinderpest.",
    “E.O. Wilson.",
    “An empty pipette.",
    “Nudibranchs.",
    “Astral projection.",
    “A 3D printed heart.",
    “Cosmic microwave background radiation.",
    “Nuclear waste.",
    “Traumatic insemination.",
    “A significant increase in entropy.",
    “Carl Sagan's turtlenecks.",
    “Reviewer 3.",
    “Tardigrades.",
    “The control group.",
    “A gravitational lens.",
    “An impact crater.",
    “Crashing into the Sun.",
    “Nanotechnology.",
    “No-one knows.",
    “Dissolved in a vial of hydrochloric acid.",
    “Lab rotation students.",
    “Internet arguments about Richard Dawkins.",
    “A DNA ladder.",
    “A supermassive black hole.",
    “The 10 Inuit words for sperm.",
    “Irrefutable proof of life on Mars.",
    “A learning opportunity.",
    “Fundamental discord between theory and experiment leading to a paradigm shift.",
    “Evidence that there really is a God.",
    “Professor Richard Dawkins.",
    “42.",
    “Newton's virginity.",
    “Brain parasites.",
    “The Pauli exclusion principle.",
    “Hypermatter annihilation reaction.",
    “Church of Scientology.",
    “Violent relaxation.",
    “Mice with tumors on their butts.",
    “Falsifying data.",
    “Nature cover.",
    “Hunger strike when I don't get tenure.",
    “RNAsses.",
    “Pipette fatigue.",
    “Stephen Pinker's hair.",
    “Integral charts.",
    “Lab coat stains.",
    “Getting scooped.",
    “Laser spot damage.",
    “Centrifuge tubes.",
    “p < 0.05.",
    “Machine learning buttressed Bayesian statistical inference.",
    “Schrodinger's cat.",
    “Genome.",
    “Cleaning up after sex on the Space Shuttle.",
    “Gravity, sponsored by Red Bull.",
    “A hairless black hole.",
    “Gneiss cleavage.",
    “Edwin Hubble's expanding shaft.",
    “Watson and Crick slash/fic.",
    “Robert Boyle's passed gas.",
    “Isaac Newton's nocturnal emissions.",
    “LIGO.",
    “Soft money.",
    “Leftover pizza.",
    “Utter and complete lack of faculty presence at social activities.",
    “Two-body problem.",
    “Blood-stained lab coat.",
    “Unethical bastardization of the scientific method.",
    “TMNT ooze.",
    “Friggin black holes, man!",
    “Quantum teleportation.",
    “Tachyons, bitch.",
    “Positronic neural net. It's a real thing!",
    “Cold fusion.",
    “Magnetic monopoles. That's right, plural!",
    “Your advisor marrying one of his other graduate students, who started after you did.",
    “Astronomers attempting to dance.",
    “That one guy everyone in the field hates but who publishes way too damn often somehow.",
    “Conference hookups.",
    “Overwhelming incomprehensible overcommitment.",
    “Wet mergers with dynamical friction.",
    “The Leidenfrost Effect.",
    “Onions.",
    “Scientology.",
    “The Caspian Sea.",
    “The Matrix.",
    “Kansas Dept. of Education.",
    “National Science Foundation.",
    “A well sharpened pencil.",
    “Autoclave.",
    “Natural selection!",
    “Darwin.",
    “A crescent moon.",
    “Phalanges banging.",
    “Alan Turing's last blowjob.",
    “Brightly coloured liquids.",
    “Uranus.",
    “The Cosmological Constant.",
    “Black Hole.",
    “Bilateral symmetry.",
    “A Petri dish full of spermatozoa.",
    “A two-headed snake.",
    “A corkscrew duck penis.",
    “Evolution gone awry.",
    “Cosmic strings.",
    “Van Allen belt.",
    “Reprogrammed stem cells.",
    “Microscopic black holes.",
    “40-gallon drum of nuclear waste.",
    “David Attenborough's vocal stylings.",
    “Mice sprouting tumors.",
    “Asymmetrical body parts.",
    “Interstellar space.",
    “The Scoville scale of pepper hotness.",
    “Fecal transplants.",
    “Crime scene DNA.",
    “Nanoparticle swarms.",
    “Grey goo.",
    “Solar flares.",
    “Robot overlords.",
    “Amber encased insect.",
    “Humpback whale song.",
    “Mosquitofish.",
    “Donor organs.",
    “Invasive carp.",
    “Undifferentiated stem cells.",
    “Cosmic inflation.",
    “Fractured metatarsals.",
    “Mad cow disease.",
    “Electroshocking earthworms.",
    “Cocaine ordered from Sigma Aldrich.",
    “Tetrahydrocannibinol.",
    “A jar of leeches.",
    “Replacing polymerase enzyme with rancid komodo dragon saliva.",
    “A gravitational constant string.",
    “Passing out on lab ethanol.",
    “The metric system.",
    “A spontaneous fission reaction.",
    “Pickle juice.",
    “Answers in Genesis.",
    “Neil DeGrasse Tyson.",
    “Autism caused by vaccinations.",
    “Creationists.",
    “Isaac Newton's third law of first dates.",
    “The control group.",
    “Unicorns.",
    “Going inside soap bubbles.",
    “Opposable thumbs.",
    “Carl Sagan's frustrated desire to become a tarot card reader.",
    “Phylum Echinodermata.",
    “Sea squirts.",
    “Coughing on your labmate's plate of primary cells.",
    “Presenting your data in Comic Sans.",
    “Prancing about in a bunny suit in the BSL-3 lab.",
    “Making out with the lab hottie in the dark room.",
    “An inverse correlation between error bar size and penile length.",
    “Bonobo sex.",
    “Schrodinger's Cat.",
    “A grad student with nothing to lose.",
    “Awkward advisor interaction.",
    “MRSA.",
    “Chlamydia.",
    “Spaghettification.",
    “The radioactive, undead corspe Marie Curie back from the grave, out for revenge.",
    “Maxwell's demon.",
    “Statisticians with haemorrhoids.",
    “Testing bunnies with cosmetics.",
    “Artificial insemination.",
    “Excess production of methane.",
    “Free radicals.",
    “Flatlining brain.",
    “Stonehenge.",
    “Methane from cows.",
    “A type Ia supernova.",
    “A temporal anomaly.",
    “Lab hazing.",
    “Schrodinger's cattery.",
    “Undergrads.",
    “Mice that eat their babies.",
    “Putting dry ice in Eppendorf tubes.",
    “Pavlov's doggy daycare.",
    “Explosive testes.",
    “Experimenting on yourself.",
    “Three gallons of pure ethanol.",
    “\”Field\” work.",
    “Accidentally falling in a volcano.",
    “Eating your model system.",
    “Eating your model organism.",
    “Your pervy advisor.",
    “Steven Hawking talking dirty.",
    “John Gurdon's hair.",
    “Taking shots from the 70% ethanol.",
    “Falsifying data.",
    “Herpes.",
    “Sequencing your own DNA.",
    “Watching fruit flies having sex.",
    “Spit in a tube.",
    “Jizz in a tube.",
    “Jerk off in an MRI.",
    “Weigh mouse poop.",
    “Fucking in zero gravity.",
    “Robot sex.",
    “Gonads.",
    “Blowing shit up.",
    “Stashing a sixpack in the lab fridge.",
    “Indescribable frustration.",
    “Growing pot in the greenhouse.",
    “Getting stopped by airport security because of the chemicals on your shoes.",
    “\”The Elements\” by Tom Lehrer.",
    “p=0.06.",
    “A spider the size of your face.",
    “An everted seastar stomach.",
    “A new state of matter.",
    “Pornographic looking cloud.",
    “Untethered spacewalk.",
    “Plasma surfing on solar flares.",
    “Exploitative advisor.",
    “Measuring the diameter of a penguin's anus and winning an Ignobel for the trouble.",
    “Bigfoot's DNA sequence.",
    “The Ablation Cascade.",
    “Self Replicating Mystery Meat.",
    “Dihydrogen Monoxide.",
    “A supermassive black hole with a taste for human blood.",
    “A back of the envelope calculation.",
    “My major professor.",
    “Confirmation bias.",
    “Long, rambling questions after a conference talk.",
    “Satellites.",
    “A human subject (i.e. myself).",
    “My messy lab.",
    “Reviewers.",
    “Highly cited papers.",
    “Distracting grammatical errors.",
    “The scientific method.",
    “Diuretic shellfish poisoning.",
    “I'm Bill Nye, BIATCH!",
    “All the ethanol went missing.",
    “Pythagoras's NEW theorem.",
    “Because the Bible says so.",
    “Sea level rising...In my pants.",
    “Birdemic.",
    “That's a big pipette.",
    “Texas textbooks.",
    “We're gonna need a bigger fulcrum.",
    “Not enough replicates.",
    “Antibioticresistant gonorrhea.",
    “Spontaneous combustion of fecal matter.",
    “An analytic solution of the Navier-Stokes equation as applied to explosive diarrhea.",
    “Blowfish.",
    “Nads the size of Jupiter.",
    “Hearing a number such as 10000 and wondering what it is in binary.",
    “Watching a baseball game and plotting trajectories in your head.",
    “Sprinkling salt on sliced tomatoes and thinking, "Osmois at work!"",
    “Speaking out loud in chemical formulas. To yourself.",
    “Cloacal protuberance.",
    “Cloacal kiss.",
    “Great tits.",
    “Amphiphile.",
    “Electrical fires.",
    “Undergrads.",
    “Liquid nitrogen.",
    “Traumatic insemination.",
    “Sequential hermaphroditism.",
    “Killer cells.",
    “Protein injection.",
    “Static electricity.",
    “Gravity ripples.",
    “Serial monogamy.",
    “Regression to the mean.",
    “Total Maximum Daily Load.",
    “Contagious yawning.",
    “Awkward lab parties.",
    “Legless lizards.",
    “Physics envy.",
    “Arachnophobic entomologists.",
    “Topological insulators.",
    “Brain-eating proteins.",
    “Bremsstrahlung.",
    “Prostate dysfunction.",
    “H5N1 pandemic avian flu.",
    “Leaky barrels of nuclear waste.",
    “Mind-bending quantum paradoxes.",
    “In precise terms, deady, deady, dead dead.",
    “Just some goddamn cells, ok?",
    “The God Delusion.",
    “Shitty verbal on the GRE.",
    “The moon.",
    “Vaginal secretions.",
    “A USB, some Red Bull knock-off, and the homeliest lab tech.",
    “The footnotes.",
    “A horrifying cat that is both dead and alive.",
    “The unparalleled genius of Albert Einstein's ball sack.",
    “Ed Witten practicing shibari with Leonard Susskind.",
    “Climate change denial.",
    “Another goddam postdoc.",
    “Bill Nye's bowtie.",
    “High-fiving a robot arm.",
    “Mercury fulminate disguised as crystal meth.",
    “A mouse growing a human ear on its back.",
    “A research monkey that is smarter than the lab assistant.",
    “Pouring liquid nitrogen down the back of someone's shirt.",
    “A lab mouse that simply refuses to die.",
    “Stain-covered lab coats.",
    “Koko the gorilla's kittens.",
    “An illegibly labeled specimen.",
    “Melting sea ice.",
    “A lab full of hot undergrad interns.",
    “Agar shot.",
]

bcards-science = [
